name: alienzone
version: 0.0.33
description:
  Space Crystal Matching Puzzle
author: brucedavidson <darkoverlordofdata@gmail.com>
homepage: http://darkoverlordofdata.com
dependencies:
  browser: any
  yaml: any
  play_phaser:
    git: git://github.com/darkoverlordofdata/play_phaser.git

  play_pixi: any
  dartemis: any
  dilithium:
    git: git://github.com/darkoverlordofdata/dilithium.git
  mt19937: any
  match3:  any


transformers:
- $dart2js:
    checked: false
    minify: true
    suppressWarnings: false
    suppressHints: false
    terse: false
    verbose: true
    csp: true
