name: alienzone
version: 0.0.3
description:
  Match 3 game
author: brucedavidson <darkoverlordofdata@gmail.com>
homepage: http://darkoverlordofdata.com
dependencies:
  browser: any
  yaml: any
  play_phaser: any
  play_pixi: any
  rikulo_gap: any
  match3: any
  dilithium: any
#    path: ../dilithium
#    git: git@github.com:darkoverlordofdata/dilithium.git

transformers:
- $dart2js:
    checked: false
    minify: true
    suppressWarnings: false
    suppressHints: false
    terse: false
    verbose: true
    csp: true
