name: alienzone
version: 0.0.3
description:
  Match 3 Puzzle Game
author: brucedavidson <darkoverlordofdata@gmail.com>
homepage: http://darkoverlordofdata.com
dependencies:
  browser: any
  yaml: any
  play_phaser: ">=0.10.0 <0.11.0"
  play_pixi: any
  match3:  any
  dilithium: #any
    path: ../dilithium

transformers:
- $dart2js:
    checked: false
    minify: true
    suppressWarnings: false
    suppressHints: false
    terse: false
    verbose: true
    csp: true
