name: alienzed
version: 0.0.1
description:
  Match 3 game
author: brucedavidson <darkoverlordofdata@gmail.com>
homepage: http://darkoverlordofdata.com
dependencies:
  js: "<0.3.0"
  browser: ">=0.10.0+2 <0.11.0"
  play_pixi: any
  rikulo_gap:

transformers:
- $dart2js:
    checked: false
    minify: false
    suppressWarnings: false
    suppressHints: false
    terse: false
    verbose: true