name: alienzone
version: 0.0.9
description:
  Space Crystal Matching Puzzle
author: brucedavidson <darkoverlordofdata@gmail.com>
homepage: http://darkoverlordofdata.com
dependencies:
  browser: any
  yaml: any
  play_phaser: any
  play_pixi: any
  dartemis: any
  match3:  #any
    path: ../match3
  dilithium: #any
    path: ../dilithium

transformers:
- $dart2js:
    checked: false
    minify: true
    suppressWarnings: false
    suppressHints: false
    terse: false
    verbose: true
    csp: true
