name: alienzone
version: 0.0.1
description:
  Match 3 game
author: brucedavidson <darkoverlordofdata@gmail.com>
homepage: http://darkoverlordofdata.com
dependencies:
  browser: ">=0.10.0+2 <0.11.0"
  unittest: ">=0.11.0+5 <0.12.0"
  toastd: #">=1.0.0 <2.0.0"
    git: https://github.com/darkoverlordofdata/toastd
  yaml: ">=2.0.1+1 <3.0.0"
  play_phaser: ">=0.10.3+1 <0.11.0"
  play_pixi: ">=0.10.3 <0.11.0"
  rikulo_gap: ">=0.6.0+1 <0.7.0"
  match3: "0.0.4"
  dilithium: #">=0.1.0 <0.2.0"
    path: ../dilithium
#    git: git@github.com:darkoverlordofdata/dilithium.git

transformers:
- $dart2js:
    checked: false
    minify: true
    suppressWarnings: false
    suppressHints: false
    terse: false
    verbose: true
    csp: true
