#+--------------------------------------------------------------------+
#| config.yaml
#+--------------------------------------------------------------------+
#| Copyright DarkOverlordOfData (c) 2014
#+--------------------------------------------------------------------+
#|
#| This file is a part of alienzone
#|
#| alienzone is free software; you can copy, modify, and distribute
#| it under the terms of the MIT License
#|
#+--------------------------------------------------------------------+
#
# Alien Zone Dilithium(Li2) Configuration
#
#
name: Alien Zone
lang: en
paths:
  preferences: preferences/preferences.yaml
  arrays: values/arrays.yaml
  strings: values/strings.yaml

minWidth: 320
minHeight: 480
maxWidth: 640
maxHeight: 960
pageAlignHorizontally: true
pageAlignVertically: true
forceOrientation: false

splashKey: splashScreen
splashImg: images/splash.png

showPreloadBar: false
preloadBarKey: preloadBar
preloadBarImg: 
preloadBgdKey: preloadBgd
preloadBgdImg: 

images:
  background:     images/background.png
  board:          images/board.png
  icon:           images/d16a.png
  label:          images/label.png
  scores:         images/scores.png
  #  ui buttons
  playButton:     images/buttons/play1.png
  scoreButton:    images/buttons/score1.png
  creditsButton:  images/buttons/credits1.png
  optionsButton:  images/buttons/options.png
  backButton:     images/buttons/back1.png
  arrow_right:    images/arrows/right.png
  arrow_left:     images/arrows/left.png
  arrow_down:     images/arrows/down.png
  arrow_lrot:     images/arrows/lrot.png
  arrow_rrot:     images/arrows/rrot.png
  # game pieces
  gem_blue:       images/gems/blue.png
  gem_cyan:       images/gems/cyan.png
  gem_green:      images/gems/green.png
  gem_magenta:    images/gems/magenta.png
  gem_orange:     images/gems/orange.png
  gem_pink:       images/gems/pink.png
  gem_red:        images/gems/red.png
  gem_yellow:     images/gems/yellow.png

audio:
  bonus1: audio/sfx/Powerup.ogg
  bonus2: audio/sfx/Powerup2.ogg
  bonus3: audio/sfx/Powerup3.ogg
  bonus4: audio/sfx/Powerup4.ogg
  bonus5: audio/sfx/Powerup5.ogg
  bonus6: audio/sfx/Powerup6.ogg
  bonus7: audio/sfx/Powerup7.ogg
  bonus8: audio/sfx/Powerup8.ogg
  bonus9: audio/sfx/Powerup9.ogg
  bonus10: audio/sfx/Powerup10.ogg
  bonus11: audio/sfx/Powerup11.ogg
  bonus12: audio/sfx/Powerup12.ogg
  bonus13: audio/sfx/Powerup13.ogg
  bonus14: audio/sfx/Powerup14.ogg
  bonus15: audio/sfx/Powerup15.ogg
  bonus16: audio/sfx/Powerup16.ogg
  bonus17: audio/sfx/Powerup17.ogg
  bonus18: audio/sfx/Powerup18.ogg
  bonus19: audio/sfx/Powerup19.ogg
  bonus20: audio/sfx/Powerup20.ogg

sprite:
levels:
